language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_script:
  - psql -c 'create database level1;' -U postgres
  - psql -c 'create database level2;' -U postgres
  - psql -c 'create database level3;' -U postgres
